server:
  port: 12000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zefengindex/tensquare_config.git
  application:
    name: tensquare-config
  rabbitmq:
    host: 192.168.89.128
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh